[package]
name = "cf-dns-record-update"
version = "0.1.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.0"
cloudflare = "0.9.1"
env_logger = "0.9.0"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
log = "0.4.0"
openssl = { version = "0.10.38", features = ["vendored"] }
rsdns = { version = "0.13.1", features = ["net-tokio"] }
serde = { version = "1.0.133" }
serde_json = "1.0.74"
thrift =  "0.13"
tokio = { version = "1.21.0", features = ["rt", "net", "macros"] }
ureq = { version = "2.4.0", features = ["json"] }
vaultrs = "0.6.2"
