[package]
name = "dns-record-update"
version = "0.4.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
env_logger = "0.10.0"
futures-util = { version = "0.3.26", default-features = false, features = ["std"] }
google-dns1 = "4.0.1"
http = "0.2.9"
log = "0.4.0"
openssl = { version = "0.10.45", features = ["vendored"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.17.0", features = ["rt-tokio"] }
rsdns = { version = "0.14.0", features = ["net-tokio"] }
serde = { version = "1.0.156" }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "net", "macros", "signal"] }
vaultrs = "0.6.2"
